### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by bugnumber9** [yaronguez/gmw-taxonomy#2]
I downloaded and activated the plugin, but Taxonomies tab doesn't appear in GEO my WP > Settings.

**Comment by yaronguez** [comment]
Sorry i don't have time to debug this issue right now but I can say that it
definitely works for me on the latest version of WP and the latest version
of Geo My WP.  Have you confirmed that the addon is activated in Geo My WP
-> Addons?

Yaron Guez
Software Architect
(781) 249-4709

**Comment by JakeTibbits** [comment]
I'm having the same issue - downloaded and activated but taxonomies tab not showing. Tried both manual install and installing through github updater but same problem.

On the GEO my WP -> Addons page the add-on doesn't show an option to activate, just the 'Get Addon' button which leads to this repository. Screenshots attached.
![geomwp1](https://cloud.githubusercontent.com/assets/17985552/18371518/d20dcdae-762c-11e6-9c33-482903688b43.jpg)
![geomwp2](https://cloud.githubusercontent.com/assets/17985552/18371519/d20eca24-762c-11e6-9c61-10b889e44d04.jpg)

I realise you don't have a lot of time, but any advice at all would be much appreciated.

Many thanks,

Jake

**Comment by yaronguez** [comment]
I've reached out to the author of GMW to see if he can assist since I'm unable to reproduce this. I'll let you know what he says (unless he comments here directly).

**Comment by yaronguez** [comment]
In the meantime, I would try deactivating your other plugins one at a time to see if there's a conflict. I know that can be tedious but 9 times out of the 10 that's the cause of most plugin bugs. If you do find a conflict, please let me know. Thanks!

**Comment by cmoser13** [comment]
I am also experiencing the exact same conflict

**Comment by Fitoussi** [comment]
HI,
I remember seeing the issue and had a work around. But I can remember what it was.
I am going to look into this issue by tomorrow and will report back.

**Comment by JakeTibbits** [comment]
Hi,
Yaronguez - of course it was some plugin load-order conflict. I deactivated all plugins, then reactivated GMW and the Add-On, activated the add-on, then re-activated all other plugins and it works perfectly!

I should've known to try this immediately, thank you for the advice!

**Comment by cmoser13** [comment]
I did not have as much luck. Tried deactivating all plugins, also reinstalled all WMG add-ons and plugins. Changed theme to default but did not see any change. I am still getting the screen that @jakebonusmedia  posted a few days ago. The add-on appears to be missing and dose not allow you to activate it. 

Side note, my client is using WPEngine for hosting, not sure if that could have any play in the issue since I know they monitor plugins that are added. 

Thank you

**Comment by Fitoussi** [comment]
Just tested it on my site and I did have the issue at first. Please make sure the plugin's folder name is gmw-taxonomy instead of gmw-taxonomy-master. That solves the issue for me.

Let me know if that helps. Otherwise I will look into it again.

**Comment by cmoser13** [comment]
That was it. The plugin folder had master after it. 

Thanks!

**Comment by yaronguez** [comment]
Interesting. I wonder how it got there? Glad it's working!

Yaron Guez
Software Architect
(781) 249-4709

**Comment by Fitoussi** [comment]
"master" is added automatically when downloading a ZIP file from Github ( I believe ).

**Comment by yaronguez** [comment]
Ah, let me update the readme to address that. Thanks guys!

**Comment by matteo-greco** [comment]
I'm having the same issue described by @NazarH and @jakebonusmedia.

Fresh installation of WP 4.6.1
Geo My WP 2.6.6.1
Gmw-taxonomy 1.0.9 installed via GitHub Updater Plugin in the gmw-taxonomy directory
No other plugins installed

The plugin activates but the the GEO my WP > Addons page only has a "Get Add-on" button.
GEO my WP > Settings doesn't have a Taxonomies tab

Any ideas?

**Comment by yaronguez** [comment]
Did you check to ensure the plugin directory is gmw-taxonomy and not
gmw-taxonomy-master?

Yaron Guez
Software Architect
(781) 249-4709

**Comment by matteo-greco** [comment]
Yes, unfortunately that's not it. The plugin's directory name is gmw-taxonomy
